pipeline:
  name: Pipeline_as_Code
  identifier: Pipeline_as_Code_Clone
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.github
        repoName: codeplayground
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessk8sconnector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    connectorRef: account.harnessImage
                    image: node:16
                    shell: Sh
                    command: |-
                      npm install
                      npm test
                      npm audit fix --force
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Unknown
                        action:
                          type: MarkAsSuccess
